--- #YAML:1.0
name:                Term-Size-Win32
version:             0.207
abstract:            Perl extension for retrieving terminal size (Win32 version)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adriano R. Ferreira <ferreira@cpan.org>
recommends:   
    Win32::Console:                0
